name: palito_3_0
description: "Aplicación para guardar y explorar recuerdos gastronómicos."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # ---------------------------------------------------------------------------
  # UI
  # ---------------------------------------------------------------------------
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # ---------------------------------------------------------------------------
  # STATE MANAGEMENT
  # ---------------------------------------------------------------------------
  flutter_riverpod: ^2.6.1

  # ---------------------------------------------------------------------------
  # NAVIGATION
  # ---------------------------------------------------------------------------
  go_router: ^14.3.0

  # ---------------------------------------------------------------------------
  # FIREBASE
  # ---------------------------------------------------------------------------
  firebase_core: ^3.15.2
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.4.4
  sign_in_with_apple: ^6.1.4
  # ---------------------------------------------------------------------------
  # MAPS & LOCATION
  # ---------------------------------------------------------------------------
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  geolocator: ^14.0.3
  geocoding: ^2.1.0

  # ---------------------------------------------------------------------------
  # MEDIA
  # ---------------------------------------------------------------------------
  image_picker: ^1.1.2

  # ---------------------------------------------------------------------------
  # LOCAL STORAGE & FILES
  # ---------------------------------------------------------------------------
  shared_preferences: ^2.3.2
  path_provider: ^2.1.3
  path: ^1.9.0

  # ---------------------------------------------------------------------------
  # UTILITIES
  # ---------------------------------------------------------------------------
  uuid: ^4.3.3
  http: ^1.6.0
  cached_network_image: ^3.4.1
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png"
  ios: true
  android: true
  web:
    generate: true
    background_color: "#FFD400"
    theme_color: "#FFD400"
  remove_alpha_ios: true
  background_color_ios: "#FFD400"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/