// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmXz0Gh2_B4c91xj4Tmpxn5x8Xcp5YQUw',
    appId: '1:911590606586:ios:ca3f7c60b780aace356b43',
    messagingSenderId: '911590606586',
    projectId: 'palito-de-sabores',
    storageBucket: 'palito-de-sabores.firebasestorage.app',
    iosBundleId: 'com.palito.sabores',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAISRuQ8zQXePfKAqqwkxtm531y-DrTyVI',
    appId: '1:911590606586:android:5bb73d6ad969d68e356b43',
    messagingSenderId: '911590606586',
    projectId: 'palito-de-sabores',
    storageBucket: 'palito-de-sabores.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYhs1zl8byWDHJvOlHzNv6BN7BBK01psw',
    appId: '1:911590606586:web:aaab37d2012e05dc356b43',
    messagingSenderId: '911590606586',
    projectId: 'palito-de-sabores',
    authDomain: 'palito-de-sabores.firebaseapp.com',
    storageBucket: 'palito-de-sabores.firebasestorage.app',
  );
}
